import type { Metadata } from "next";
import {Vazirmatn } from "next/font/google";
import { ThemeProvider } from "@/components/provider/theme-provider";
import "../globals.css";
import NavBar from "@/components/main/navbar/navbar";
import HeroSection from "@/components/main/herosection/hero-section";
import { ModeToggle } from "@/components/dark-toggle";
import Footer from "@/components/main/footer/footer";



const font = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Darchin Caffe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning className="scroll-smooth snap-mandatory">
      <body
        className={`${font.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          storageKey="discord-theme"
          enableSystem
          disableTransitionOnChange
        >
          <main className="max-w-screen-2xl mx-auto">
            <NavBar />
            <HeroSection />
          {children}
          <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
