import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { ThemeProvider } from "@/components/provider/theme-provider";
import "../globals.css";
import ReactQueryProvider from "@/components/provider/react-query-provider";
import SideBar from "@/components/dashboard/sidebar";
import DashboardHeader from "@/components/dashboard/header";

const font = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            storageKey="discord-theme"
            enableSystem
            disableTransitionOnChange
          >
            <main className="grid grid-cols-12 md:grid-rows-[70px_1fr] grid-rows-[auto_auto_1fr] max-w-screen-2xl mx-auto h-screen">
              <DashboardHeader />
              <SideBar />
              <div className="md:col-span-9 md:row-span-1 col-span-12 bg-background h-full p-4">
                {children}
              </div>
            </main>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
