import { Vazirmatn } from "next/font/google";
import "../globals.css";

const font = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${font.className} flex flex-col items-center justify-center max-w-screen max-h-screen`}>{children}</body>
    </html>
  )
}
